### ISSUE TITLE
Consider auto-restarting Mirror after channel removed message

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/dhtproto#10]
In principle, the removal of the mirrored channel should mean the request is over. However, in practice, removal of a channel which is being actively used by an application is usually an error.

**Comment by gavin-norman-sociomantic** [comment]
Some comments from @joseph-wakeling-sociomantic:

The main concern here is about likely failure scenarios.  If someone accidentally deletes a DHT channel, then with the current `dht.neo.mirror` request behaviour, it won't suffice to regenerate that channel: either every reader app will have to be restarted (with the obvious problem that someone might forget to restart some particular app, or some individual node of that app, especially if it is not generating alerts).

Apps could of course implement their own retry attempts, but that relies on developer virtue, which is famously questionable ... ;-)

With that in mind, the safest situation is for mirror requests to auto-recover from deletion of a channel, if the channel is later recreated.  Alternative reactions to channel deletion (assuming an app that might want to do this) could then be the app-implemented exception, rather than the rule.

**Comment by gavin-norman-sociomantic** [comment]
An alternative idea to fix this issue: we prohibit RemoveChannel from deleting a channel which has any listeners (i.e. active Mirror requests).

**Comment by joseph-wakeling-sociomantic** [comment]
Yea, that could be a useful safety feature.  But does it have to be either/or? :-)

**Comment by gavin-norman-sociomantic** [comment]
Well, if RemoveChannel can never remove a channel being mirrored, then the ChannelRemoved message of the Mirror request would no longer exist and the whole question of restarting the request in this event would vanish in a puff of logic.

**Comment by joseph-wakeling-sociomantic** [comment]
@gavin-norman-sociomantic I'm taking the attitude that the mirror request should not assume good behaviour of the DHT nodes ;-)  But fair point.

**Comment by gavin-norman-sociomantic** [comment]
Haha yeah, well, we could add "something impossible happened" messages to all requests, but I think that's beyond the scope of our current work ;)

**Comment by joseph-wakeling-sociomantic** [comment]
BTW, should the "don't remove the channel" policy be limited to listen/mirror requests, or should it be for _any_ active request on the channel?

**Comment by gavin-norman-sociomantic** [comment]
Replaced by #39. (Unless that proves infeasible, for some reason, in which case we can reopen this issue.)
