### ISSUE TITLE
Provide a stable way to merge legacy releases into neo

### ISSUE THREAD

**Issue by joseph-wakeling-sociomantic** [sociomantic-tsunami/dhtproto#108]
Up until now, legacy releases have been merged into the mainline neo development branch.  This means that any neo user wanting to get the latest legacy fixes and features has to update to also accept any mainline neo development changes made in the meanwhile.

This creates a problem for applications wanting to add neo support: they are forced to choose between having support for the latest legacy protocol version, versus staying on a "stable" neo alpha release.

To avoid this it would be helpful if new legacy releases could be merged directly on top of the latest neo alpha release, ideally resulting in a new tagged alpha (`neo-alpha-N+X.y.z` where `X.y.z` is the legacy version ... ?).  This new tagged alpha would then be what gets merged into the mainline neo dev branch.

This would mean that neo pioneers could stick to the latest alpha release, but always have an opportunity to update to the latest legacy protocol release.

For convenience, I would suggest adopting this policy from neo-alpha-5 onwards.

(There's a potential sticking point here about, what if legacy makes a new major release, but then later patches the previous major release series, but we can probably negotiate that as/when we need to.  Assuming that the next major dhtproto release will predate neo-alpha-5, we can probably avoid having to face that.)

**Comment by gavin-norman-sociomantic** [comment]
Another way might be to rebase the neo branch onto each legacy release and tag it.

**Comment by gavin-norman-sociomantic** [comment]
After some discussion, here's the proposal:
* From neo-alpha-5, we create a SemVer v0.x.x branch for neo releases.
* neo-alpha-5 would be tagged as v0.5.0, and a v0.5.x branch created for bug fixes.
* Following the usual SemVer rules, v0.x.x can include breaking changes in minor releases. This would allow us to:
  - Continue fast development of DHT neo, making breaking API changes if needed.
  - Merge non-neo branches into the neo branch as required.
  - Update submodules (specifically swarm) as required.

**Comment by gavin-norman-sociomantic** [comment]
Done!

**Comment by joseph-wakeling-sociomantic** [comment]
Just to confirm: merges from stable (whether just bugfixes, or minor or major releases) would have to be done manually, right?

**Comment by gavin-norman-sociomantic** [comment]
Correct. The whole alpha branch will be maintained entirely manually.
