### ISSUE TITLE
Convert assert -> verify

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/dhtproto#111]

**Comment by leandro-lucarella-sociomantic** [comment]
Is it reasonable to expect this to be done by Q2? This is important to be able to keep moving towards D2.

**Comment by gavin-norman-sociomantic** [comment]
Yes, definitely.

**Comment by gavin-norman-sociomantic** [comment]
Addressed in #137.

**Comment by leandro-lucarella-sociomantic** [comment]
Cool! So this means that the dhtnode can be tested again in D2, or are there any other dependencies that we need to `verify()`ize first?

**Comment by gavin-norman-sociomantic** [comment]
Nope, this is the last library that the dhtnode uses. We still need to `verify()`ize the dhtnode itself, of course. See https://github.com/sociomantic-tsunami/dhtnode/milestone/9.

**Comment by gavin-norman-sociomantic** [comment]
Fixed by #137.
