### ISSUE TITLE
Extend turtle.env.Dht API to allow counting number of listeners

### ISSUE THREAD

**Issue by joseph-wakeling-sociomantic** [sociomantic-tsunami/dhtproto#180]
App test suites typically need to wait for mirror/listen requests to start before running any tests.  To support this, it would be useful for the `Dht` class to expose some means to check how many listeners (== legacy `Listen` or neo `Mirror`) requests are currently active.

Probably the ideal mechanism would be to expose an `expectListeners (istring channel, uint n, uint timeout_sec)` which would block until either the specified number of listeners are active or the timeout is reached (in which case an exception would be thrown).

This would allow app test suites to implement test cases which would validate the mirror setup.

**Comment by joseph-wakeling-sociomantic** [comment]
Note that similar ideas could probably be implemented for dlsproto and dmqproto.  This would avoid having to rely on time delay to ensure that apps are set up to receive test data.

**Comment by gavin-norman-sociomantic** [comment]
Excellent idea! Not sure why we didn't think of this before!

**Comment by joseph-wakeling-sociomantic** [comment]
JPL Institutional Coding Standard 2.7: "Do not use task delays for task synchronization" ;-)
https://lars-lab.jpl.nasa.gov/JPL_Coding_Standard_C.pdf
