### ISSUE TITLE
Prohibit RemoveChannel from deleting a channel being listened to

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/dhtproto#39]
#10 discusses problems around ending a Mirror request when the channel being mirrored is deleted. The same argument applies to the legacy Listen request.

Discussion led to the idea that it should actually be illegal to remove a channel that is being listened to. RemoveChannel is used in two cases:
1. By accident.
2. Deliberately, to remove a channel which is no longer in use.

In both cases, the request should definitely not work on a channel that's currently in use.

**Comment by joseph-wakeling-sociomantic** [comment]
Should this constraint apply only for channels being listened to, or for channels with any open request of any kind (the remove-channel request aside)?

**Comment by gavin-norman-sociomantic** [comment]
If a request for a non-existent channel is handled, the node will create the channel. For this reason, other requests aren't really affected by this issue.

**Comment by joseph-wakeling-sociomantic** [comment]
I was thinking of a `GetAll` request where the channel was removed part-way through.

**Comment by gavin-norman-sociomantic** [comment]
The request would just be cut short as all data would be removed from the storage engine.

**Comment by joseph-wakeling-sociomantic** [comment]
OK.  As long as that's an acceptable outcome from your point of view, I have no objections.  I wonder if it might be worth checking in with @scott-gibson-sociomantic though, since it's his use case that `GetAll` is there to support.

**Comment by gavin-norman-sociomantic** [comment]
We're talking about the legacy requests (including GetAll) as well.

**Comment by joseph-wakeling-sociomantic** [comment]
Yes, understood.  But since there is a neo `GetAll` I think it's worth checking in on the use-case before assuming that it's OK for it to just cut out part-way through on channel removal.

**Comment by scott-gibson-sociomantic** [comment]
Correct me if i'm wrong but doesn't neo have a `Deleted` notification in the notifier to indicate the channel was deleted? It's been a while since i looked so my memory is hazy.

**Comment by joseph-wakeling-sociomantic** [comment]
@scott-gibson-sociomantic well, we're discussing whether channel removal should be rejected if there is at least one listener still in place.  The question is whether your own neo `GetAll` use-case would also find it problematic if the channel was deleted part-way through.

**Comment by gavin-norman-sociomantic** [comment]
The point is, though, re: Listen/Mirror vs other requests, that Listen/Mirror are the only DHT requests which are supposed to be persistent (i.e. active all the time). Even relatively long-lived requests like GetAll are not active constantly and thus don't provide us with a useful indication of whether a channel is being used or not.

**Comment by joseph-wakeling-sociomantic** [comment]
@gavin-norman-sociomantic That's fair enough as a point of policy.  I just wanted to make sure that we were clear about what assumptions are made in @scott-gibson-sociomantic's use-case.

**Comment by gavin-norman-sociomantic** [comment]
This should probably be done as a breaking change: adding a new status code, `ActiveChannel` (or something), that client apps would have to handle.

**Comment by gavin-norman-sociomantic** [comment]
Unfortunately, while this is a very simple change to make, it breaks all of the legacy dhtproto tests. There's a chain of problems:
1. There's no way to end a Listen request.
2. This means that whenever a test case starts a Listen request, it remains active for the rest of the test suite's life.
3. This means that, after this point, all RemoveChannel requests will fail.
4. RemoveChannel is assigned after every test case, to ensure a clean slate for the next test, so 3. breaks all test cases after a Listen request has been assigned.

The _one_ way in which a Listen request can be stopped, from the client side, is to forcibly disconnect all connections to the node (`dht.assign(dht.disconnect(...));`. This feature has basically never been used, though, and has a lot of problems, in turn:
* It hits a bug in the connection pool whereby the shut-down connections are not properly recycled: https://github.com/sociomantic-tsunami/swarm/issues/170.
*  After disconnecting all sockets in the client, the next request to be assigned will get a connection from the pool whose socket is dead. This will lead to an I/O error upon the first attempt to write to the socket, causing the request to end with an error.
* It also seems that the node takes some time to realise that a Listen request is no longer active, after the socket has been disconnected. (I guess the node will only realise the connection is dead when a keepalive ping happens.)

All in all, it's a lot of hassle to make this work (including deep debugging / fixing of obscure and unimportant bugs in the legacy client, test suite, and fake node).

Possible directions:
1. Only make this change to the _neo_ RemoveChannel request. This would mean that, if a legacy RemoveChannel request were handled, any active Mirror requests would not realise that the channel had been removed. They'd just hang forever (even if the channel were recreated, I think).
2. Disable / remove all Listen tests. This should eradicate the problem with the test suite becoming broken.

Option 2 sounds more palatable, as a work-around.

**Comment by gavin-norman-sociomantic** [comment]
By the way, as implemented (RemoveChannel returns the Error status code if the channel is being listened / mirrored), this isn't a breaking change. (It doesn't introduce a new status code that must be handled, for example.)

**Comment by joseph-wakeling-sociomantic** [comment]
Hmmm.  Isn't the main point of concern here about whether `dht.neo.mirror` requests need to handle channel removal?

In which case, why not make it that legacy `Listen` requests do not block channel removal (since they never have in the past), but neo `Mirror` requests do (for both legacy and neo `RemoveChannel` requests)?

Wouldn't that avoid the problems described?

**Comment by gavin-norman-sociomantic** [comment]
Oh that's an interesting idea Joe. The reason why I wasn't thinking along those lines is that, at the level of the storage engine (which is where such things are noted), there is no distinction between a Listen request receiving updates on a channel vs a Mirror request receiving updates on a channel. It might be possible to add a flag to the registration, though. `block_channel_removal` or something.

**Comment by gavin-norman-sociomantic** [comment]
Though I think preventing RemoveChannel from removing a channel being Listened to is actually a nice feature to have, as well.

**Comment by joseph-wakeling-sociomantic** [comment]
The other thought was that, assuming these are turtle tests that are the problem: it's always possible to implement a separate test suite for the `Listen` requests.  So, instead of removing a channel and then doing a follow-up test, you'd be starting up a fresh `dhtnode` in a fresh sandbox.

**Comment by joseph-wakeling-sociomantic** [comment]
> Though I think preventing RemoveChannel from removing a channel being Listened to is actually a nice feature to have, as well.

I agree, but I also think that it's not necessary in the same way that it is for neo.

**Comment by gavin-norman-sociomantic** [comment]
>The other thought was that, assuming these are turtle tests that are the problem: it's always possible to implement a separate test suite for the Listen requests.

:+1: this might actually be the cleanest solution.

**Comment by joseph-wakeling-sociomantic** [comment]
> this might actually be the cleanest solution.

Yup.  And it might honestly be the best means to get the "clean slate" for dhtnode tests in general (assuming that the cost of starting a separate test-suite binary, and separate node binary and sandbox, are not so great).

Then, `RemoveChannel` becomes just another thing to test, instead of something whose correctness you're relying on for your tests to work properly.

Beyond the scope of this current PR and issue, of course ;-)

**Comment by gavin-norman-sociomantic** [comment]
Moved out of the current milestone. We'll address this once legacy requests are no longer supported. See https://github.com/sociomantic-tsunami/dhtproto/pull/61#issuecomment-343895187.

**Comment by gavin-norman-sociomantic** [comment]
When we come to address this issue, we should:
* Make a new version of RemoveChannel that refuses to remove a mirrored channel (new notification type).
* Make a new version of Mirror without the channel removed handling (removed notification types).

That way, a clean transition is possible.

**Comment by gavin-norman-sociomantic** [comment]
RemoveChannel will probably be removed entirely and replaced with a unix socket command. See https://github.com/sociomantic-tsunami/dhtproto/issues/191.
