### ISSUE TITLE
Neo Get usage examples are missing how to access the received value.

### ISSUE THREAD

**Issue by scott-gibson-sociomantic** [sociomantic-tsunami/dhtproto#52]
Only 1 of the usage examples for neo GetRequest contain information on how to access the received value. 
 
Missing
https://github.com/sociomantic-tsunami/dhtproto/blob/neo/src/dhtproto/client/UsageExamples.d#L297
https://github.com/sociomantic-tsunami/dhtproto/blob/neo/src/dhtproto/client/UsageExamples.d#L404

Exists.
https://github.com/sociomantic-tsunami/dhtproto/blob/neo/src/dhtproto/client/UsageExamples.d#L341

**Comment by gavin-norman-sociomantic** [comment]
Fixed by #53.
