### ISSUE TITLE
Make record size limit less brittle

### ISSUE THREAD

**Issue by gavin-norman-sociomantic** [sociomantic-tsunami/dhtproto#75]
Currently, the record size limit is a compile-time constant that is required by the record batcher (which rejects records that don't fit in a batch).

Steps to make this less brittle:
* [ ] Remove restriction on batch size in client-side `RecordBatch` (https://github.com/sociomantic-tsunami/swarm/pull/281)
* [ ] Increase the size of the node-side record batches.
* [ ] Increase size of Put request's record size limit to <= the updated size of the record batches.

**Future plans:**
We have [plans to implement a new record batcher](https://github.com/sociomantic-tsunami/swarm/issues/158), which will be used in the neo protocol. One of the aims of this is to allow the batch size limit (= the record size limit) to be configurable (and changeable) at runtime.

This would make changing the record size limit much easier.

When this is done, we can remove any client-side code that rejects records based on their size. (e.g. https://github.com/sociomantic-tsunami/dhtproto/blob/neo/src/dhtproto/client/request/internal/Put.d#L140-L144)

**Comment by nemanja-boric-sociomantic** [comment]
I wonder if we could have another meta-request which client could use to query the node to get the maximum record size supported (and possibly other settings in the future).

**Comment by gavin-norman-sociomantic** [comment]
Puh, I'm trying to move away from meta requests where possible. What use case could you imagine for this? i.e. what would a client do with the knowledge?

**Comment by nemanja-boric-sociomantic** [comment]
It's not a big deal, but one thing would be that the client could outright reject the records, without sending them to the node and validating their size there. And given that `GetResponsibleHashRange` (or whatever the name is) is already long-lived request, node could just send another message via the same channel to inform clients about its state/limitations. I'm not sure if it's worth additional complexity.

**Comment by gavin-norman-sociomantic** [comment]
>the client could outright reject the records, without sending them to the node and validating their size there

That reminds me: currently the client _is_ the one doing this check. (e.g. https://github.com/sociomantic-tsunami/dhtproto/blob/neo/src/dhtproto/client/request/internal/Put.d#L140-L144)

**Comment by gavin-norman-sociomantic** [comment]
My point is, though, that it doesn't really matter _who_ rejects the record (client / node). What matters is what the client can do about it. I think the answer is probably "nothing", thus having explicit knowledge of the size limit probably doesn't help.

**Comment by nemanja-boric-sociomantic** [comment]
It could matter, though, if there's a lot of huge records being transferred. But let's cross that bridge when we get to it.

**Comment by gavin-norman-sociomantic** [comment]
Yeah, for me just making the size (runtime) configurable on the node-side is a huge step forward. Propagating the size limit to the client could be a future enhancement, if it's ever needed.

**Comment by gavin-norman-sociomantic** [comment]
An update on this:
* The neo record batcher implemented in swarm has a soft size limit that is set at run-time. Records that are larger than the size limit may still be sent in a batch. See https://github.com/sociomantic-tsunami/swarm/blob/v4.x.x/src/swarm/neo/util/Batch.d#L12-L17.
* We could investigate using this new record batcher in the legacy requests, as well.
* Due to the lack of versioning in the legacy protocol, though, this would be a breaking change.

**Comment by gavin-norman-sociomantic** [comment]
Looking at the record batcher code in swarm:
* The node side uses the batch size limit in one place: https://github.com/sociomantic-tsunami/swarm/blob/v4.x.x/src/swarm/util/RecordBatcher.d#L447-L455. This check is essential to the current logic of the record batcher (i.e. it needs a way to tell whether a record will fit in the batch or not), and could not be removed without a major refactoring (which I wouldn't recommend at this time).
* The client side only uses the batch size limit in one place: https://github.com/sociomantic-tsunami/swarm/blob/v4.x.x/src/swarm/util/RecordBatcher.d#L506. This check appears to be arbitrary. It doesn't affect the actual protocol or parsing.

So, it looks like simply removing the assertion on the batch size in the client would allow the client to handle batches of any size. Of course, all active clients (or at least those doing GetAll requests) would need to be updated to this change before the batch size limit in the node could be increased.

**Comment by gavin-norman-sociomantic** [comment]
This cannot be achieved in dhtproto v13.3.0, as two of the required steps ("Remove restriction on batch size in client-side RecordBatch" and "Increase size of Put request's record size limit") require changes in swarm, thence submodule updates in dhtproto.

**Comment by gavin-norman-sociomantic** [comment]
This isn't really a change that has anything to do with dhtproto directly; it's all about updating apps to use specific swarm versions. Closing.
